---
abstract: 'Padre support for perl XS (and perlapi)'
author:
  - 'Steffen Mueller <smueller@cpan.org>'
  - 'Ahmad M. Zawawi <ahmad.zawawi@gmail.com>'
build_requires:
  Locale::Msgfmt: 0.14
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102342, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Padre-Plugin-XS
requires:
  Padre: 0.57
  Perl::APIReference: 0.04
resources:
  homepage: http://padre.perlide.org
  repository: http://svn.perlide.org/padre/trunk/Padre-Plugin-XS/
version: 0.06
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Filter/GatherDir'
      version: 4.102342
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/PruneCruft'
      version: 4.102342
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/ManifestSkip'
      version: 4.102342
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/MetaYAML'
      version: 4.102342
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/License'
      version: 4.102342
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Filter/Readme'
      version: 4.102342
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Filter/ExtraTests'
      version: 4.102342
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/ExecDir'
      version: 4.102342
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/ShareDir'
      version: 4.102342
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/Manifest'
      version: 4.102342
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/TestRelease'
      version: 4.102342
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/ConfirmRelease'
      version: 4.102342
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/UploadToCPAN'
      version: 4.102342
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: TestRequires
      version: 4.102342
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: 4.102342
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: CheckChangeLog
      version: 0.01
    -
      class: Dist::Zilla::Plugin::CheckChangesTests
      name: CheckChangesTests
      version: 1.100900
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: CompileTests
      version: 1.101800
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: PodWeaver
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: PkgVersion
      version: 4.102342
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: 4.102342
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: 4.102342
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: 4.102342
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: NextRelease
      version: 4.102342
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: PodSyntaxTests
      version: 4.102342
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: ModuleBuild
      version: 4.102342
    -
      class: Dist::Zilla::Plugin::LocaleMsgfmt
      name: LocaleMsgfmt
      version: 1.100970
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.102342
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.102342
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.102342
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.102342
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.102342
